version: '3.0'
services:
  app:
    build: .
    command: npm run start:prod
    deploy: 
      resources: 
        limits:
          cpus: '0.5'
          memory: 256M
    ports:
      - "3001:3001"
      - "3000:3000"