# fly.toml file generated for talktime on 2023-04-14T13:14:11+03:00

app = "talktime"
kill_timeout = 0
primary_region = "waw"

[[services]]
  protocol = "tcp"
  internal_port = 3001

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    restart_limit = 0

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "60µs"
    restart_limit = 0

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "180µs"
    restart_limit = 3
